services:
  minio:
    hostname: minio
    image: "minio/minio"
    container_name: minio_vnexpress  
    ports:
      - "9002:9001"  
      - "9003:9000" 
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - ./minio:/data
    env_file:
      - env
    networks:
      - vnexpress_network
    restart: unless-stopped

  mc:
    image: minio/mc
    hostname: mc
    env_file:
      - env
    entrypoint: >
      /bin/sh -c "until (/usr/bin/mc config host add minio http://minio:9000 minio minio123) do echo '...waiting...' && sleep 1; done; /usr/bin/mc mb minio/vnexpress; /usr/bin/mc policy set public minio/vnexpress; exit 0;"
    depends_on:
      - minio
    networks:
      - vnexpress_network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - minio
    networks:
      - vnexpress_network

networks:
  vnexpress_network:
    driver: bridge
    name: vnexpress_network
